### ISSUE TITLE
Test if the edmf problem is illconditioned

### ISSUE THREAD

**Issue by trontrytel** [CliMA/ClimaAtmos.jl#1155]
Compute the condition number for Bomex test case.

**Comment by dennisYatunin** [comment]
I have computed a bunch of condition numbers for the JFNK Bomex test case using [ClimaTimeSteppers PR #86](https://github.com/CliMA/ClimaTimeSteppers.jl/pull/86). As expected, the condition numbers are higher when using IMEX EDMF than when using explicit EDMF. In addition to increasing the values of the condition numbers, using IMEX EDMF also greatly increases their _variance_. This is summarized in the table below, which shows the extrema of the condition numbers with and without the preconditioner for the first 1200 seconds of simulation time for several configurations, along with the extrema of the amount by which the preconditioner reduces the condition numbers. In each case, the preconditioner is the Jacobian approximation for the dycore.

| Explicit/IMEX EDMF, dt, Newton iterations, `jvp_step_adjustment` | With Preconditioner | Without Preconditioner | Reduction Due To Preconditioner |
| :---: | :---: | :---: | :---: |
| Explicit, 40 seconds, 1, 1.0 | 1.062e12–1.069e12 | 3.817e13–3.832e13 | 35.85–35.93 |
| IMEX, 40 seconds, 1, 1.0 | N/A | N/A | N/A |
| IMEX, 40 seconds, 1, 0.1 | 1.1e13–1.4e15 | 9.9e13–5.5e15 | 1.9–9.3 |
| IMEX, 40 seconds, 1, 0.01 | 2.9e12–1.4e16 | 4.9e13–2.4e16 | 1.8–18 |
| IMEX, 100 seconds, 10, 1.0 | N/A | N/A | N/A |
| IMEX, 100 seconds, 10, 0.1 | 1.3e13–1.4e16 | 1.9e14–6.4e16 | 1.8–17 |
| IMEX, 100 seconds, 10, 0.01 | 6.2e12–9.2e17 | 1.3e14–1.7e18 | 1.8–41 |

The IMEX EDMF configurations that do not scale down the Jacobian-vector product finite difference approximation step size throw an error when computing the Jacobian matrix on the third or fourth linear solve of the first timestep. This is because computing the Jacobian requires adding vectors of the form `[0, ..., 0, ε, 0, ..., 0]` to the state `Y`. If `ε` is not sufficiently small, this can result in non-physical states; i.e., states for which saturation adjustment throws an error. Apparently, the default value of `ε` is not sufficiently small for these configurations, but this can be remedied by scaling it down by, say, 0.1 or 0.01.

Since the configurations that scale the step size down by 0.1 exhibit less variance in the condition number than those that scale it down by 0.01, one would expect them to be more likely to run to completion. However, this is exactly the opposite of what was observed—the configurations that scale the step size down by 0.1 crash one or two timesteps after reaching 1200 seconds, while those that scale it down by 0.01 run to completion. The results for the final 1200 seconds of each simulation are shown in the table below.

| Explicit/IMEX, dt, Newton iterations, `jvp_step_adjustment` | With Preconditioner | Without Preconditioner | Reduction Due To Preconditioner |
| :---: | :---: | :---: | :---: |
| Explicit, 40 seconds, 1, 1.0 | 1.093e12–1.100e12 | 3.851e13–3.865e13 | 35.15–35.22 |
| IMEX, 40 seconds, 1, 1.0 | N/A | N/A | N/A |
| IMEX, 40 seconds, 1, 0.1 | N/A | N/A | N/A |
| IMEX, 40 seconds, 1, 0.01 | 3.3e13–4.5e13 | 2.2e14–2.7e14 | 6.1–6.9 |
| IMEX, 100 seconds, 10, 1.0 | N/A | N/A | N/A |
| IMEX, 100 seconds, 10, 0.1 | N/A | N/A | N/A |
| IMEX, 100 seconds, 10, 0.01 | 9.9e13–1.7e14 | 7.8e14–1.2e15 | 6.9–8.1 |

This shows that the variance of the condition numbers of IMEX EDMF simulations decreases as the simulations progress, but it never drops to the level of explicit EDMF simulations.

Also, it does not look like the condition numbers decreased during the 10 Newton iterations of each nonlinear solve in the successful IMEX EDMF simulation with a 100 second timestep. For example, the condition numbers (with the preconditioner) of the first nonlinear solve in that simulation were `[2.1e14, 4.7e14, 6.0e13, 1.2e15, 1.5e15, 1.8e15, 1.5e16, 3.0e15, 1.7e15, 1.2e15]`, and the condition numbers of the last nonlinear solve were `[1.061e14, 9.888e13, 1.069e14, 1.075e14, 1.080e14, 1.081e14, 1.080e14, 1.080e14, 1.081e14, 1.081e14]`.

Finally, it should be noted that running these simulations a few hundred times could generate an alternative set of results due to nondeterminism, so these results should be taken with a grain of salt.

@tapios @trontrytel @Zhengyu-Huang

**Comment by dennisYatunin** [comment]
I have generated some additional condition numbers per requests from @Zhengyu-Huang and @charleskawczynski.

First, I re-ran the explicit EDMF configuration after commenting out the call to `additional_tendency` in the explicit tendency function, so that only the dycore (advection) explicit tendencies were included in the explicit tendency function. This resulted in roughly the same condition numbers as the explicit EDMF configuration, which is to be expected because the implicit tendency was identical in both cases (it only included the dycore implicit tendency).

Second, I re-ran the IMEX EDMF configurations with a timestep of 75 seconds. This time, the configuration with `jvp_step_adjustment = 0.1` did not even survive to 1200 seconds; it threw an error somewhere between 600 and 900 seconds while computing the condition number, for the same reason as the configurations with `jvp_step_adjustment = 1` have thrown errors. The configuration with `jvp_step_adjustment = 0.01` successfully ran to completion, though. Interestingly, this configuration resulted in some linear solves for which the preconditioner slightly increased the condition number instead of decreasing it.

The updated table for the first 1200 seconds of simulation time is now

| EDMF configuration, dt, Newton iterations, `jvp_step_adjustment` | With Preconditioner | Without Preconditioner | Reduction Due To Preconditioner |
| :---: | :---: | :---: | :---: |
| None, 40 seconds, 1, 1.0 | 1.06264e12–1.06266e12 | 3.81827e13–3.81828e13 | 35.9314–35.9319 |
| Explicit, 40 seconds, 1, 1.0 | 1.062e12–1.069e12 | 3.817e13–3.832e13 | 35.85–35.93 |
| IMEX, 40 seconds, 1, 1.0 | N/A | N/A | N/A |
| IMEX, 40 seconds, 1, 0.1 | 1.1e13–1.4e15 | 9.9e13–5.5e15 | 1.9–9.3 |
| IMEX, 40 seconds, 1, 0.01 | 2.9e12–1.4e16 | 4.9e13–2.4e16 | 1.8–18 |
| IMEX, 75 seconds, 10, 1.0 | N/A | N/A | N/A |
| IMEX, 75 seconds, 10, 0.1 | N/A | N/A | N/A |
| IMEX, 75 seconds, 10, 0.01 | 8.5e12–2.6e16 | 1.3e14–8.1e16 | 0.997–16 |
| IMEX, 100 seconds, 10, 1.0 | N/A | N/A | N/A |
| IMEX, 100 seconds, 10, 0.1 | 1.3e13–1.4e16 | 1.9e14–6.4e16 | 1.8–17 |
| IMEX, 100 seconds, 10, 0.01 | 6.2e12–9.2e17 | 1.3e14–1.7e18 | 1.8–41 |

The updated table for the final 1200 seconds of simulation time is now

| EDMF configuration, dt, Newton iterations, `jvp_step_adjustment` | With Preconditioner | Without Preconditioner | Reduction Due To Preconditioner |
| :---: | :---: | :---: | :---: |
| None, 40 seconds, 1, 1.0 | 1.06264e12–1.06266e12 | 3.81827e13–3.81828e13 | 35.9312–35.9319 |
| Explicit, 40 seconds, 1, 1.0 | 1.093e12–1.100e12 | 3.851e13–3.865e13 | 35.15–35.22 |
| IMEX, 40 seconds, 1, 1.0 | N/A | N/A | N/A |
| IMEX, 40 seconds, 1, 0.1 | N/A | N/A | N/A |
| IMEX, 40 seconds, 1, 0.01 | 3.3e13–4.5e13 | 2.2e14–2.7e14 | 6.1–6.9 |
| IMEX, 75 seconds, 10, 1.0 | N/A | N/A | N/A |
| IMEX, 75 seconds, 10, 0.1 | N/A | N/A | N/A |
| IMEX, 75 seconds, 10, 0.01 | 6.8e13–7.5e13 | 5.3e14–5.8e14 | 7.6–7.8 |
| IMEX, 100 seconds, 10, 1.0 | N/A | N/A | N/A |
| IMEX, 100 seconds, 10, 0.1 | N/A | N/A | N/A |
| IMEX, 100 seconds, 10, 0.01 | 9.9e13–1.7e14 | 7.8e14–1.2e15 | 6.9–8.1 |

@charleskawczynski was wondering whether the condition numbers grow quadratically with respect to the timestep. If we (somewhat arbitrarily) look at the condition numbers of the last linear solves in each of the three IMEX EDMF simulations that successfully ran to completion, we get

| dt | With Preconditioner | Without Preconditioner |
| :---: | :---: | :---: |
| 40 seconds | 3.6e13 | 2.4e14 |
| 75 seconds | 7.4e13 | 5.7e14 |
| 100 seconds | 1.08e14 | 8.6e14 |

It's a bit hard to tell, but this seems to be more linear than it is quadratic. Not sure what we can infer from that, though.
