### ISSUE TITLE
Resurface old kinetic energy in box (with bump) but no pressure gradients test

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaAtmos.jl#1455]

**Comment by szy21** [comment]
@akshaysridhar This is not closed by the PR right?

**Comment by akshaysridhar** [comment]
Right - this will now be a separate result (independent of the merged branches since we need hardcoded pressure gradients for that test)

**Comment by szy21** [comment]
> Right - this will now be a separate result (independent of the merged branches since we need hardcoded pressure gradients for that test)

Thanks. Let me know when the branch for this test is ready, and we can close this issue then.

**Comment by akshaysridhar** [comment]
In branch `as/show-ekin-cons`
(1) Terms associated with pressure gradients are turned off (the gravity parameter is also overridden), and an isothermal initial state is prescribed.
(2) A configuration with the Agnesi mountain profile is tested in a `1000s` run. 
(3) A statement to check the conservation of kinetic energy is included in the `check_conservation` driver block.  The `compute_kinetic!` function is used so that this evaluation method is identical to that within the precomputed quantities in a standard run.  

(The exact command line args used to trigger each test is included in the `pipeline.yml` file.)

Using the `sum` function defined for spectral methods - the relative change in specific kinetic energy is `2.7306671f-6` unstretched mesh config, and `-1.137778f-6` in stretched-mesh configurations. 

cc @Zhengyu-Huang @szy21

**Comment by szy21** [comment]
Thanks @akshaysridhar! I see in the pipeline that this is Float32? Would the error be smaller with Float64?

**Comment by akshaysridhar** [comment]
The relative KE error with Float64 
(1) -1.0035818460741927e-8 (unstretched config)
(2) -1.0064416449111728e-8 (stretched config)

**Comment by szy21** [comment]
Tapio suggested that we run a longer run to see if there is a trend in KE.

**Comment by Zhengyu-Huang** [comment]
Any longer run results？

**Comment by akshaysridhar** [comment]
_20 hrs, explicit solve, isothermal prescribed initial flow in a box._
![energy_cons](https://user-images.githubusercontent.com/43710045/235206379-72638f19-1361-4731-92a6-a24e73f3da6c.png)

**Comment by szy21** [comment]
Looks good, thanks!
