### ISSUE TITLE
Test using total energy in the updraft equations (not in second order terms)

### ISSUE THREAD

**Issue by trontrytel** [CliMA/ClimaAtmos.jl#1471]

**Comment by szy21** [comment]
Things to try:

- [ ] Start from non-zero a for `\rhoae_tot`: 
not working, because a will be set to zero by filter when w=0
- [ ] Add `-p (\partial a/\partial t)` term to `\rhoae_tot` tendency
  - Use  `(-p/\rho_gm) (\partial \rhoa / \partial t)` as an approximation
  not working, `e_tot` still becomes large at some point
  - Try using the exact term by adding previous a to cache 
- [ ] Use `\rhoah_tot` or entropy variables as prognostic variable
