### ISSUE TITLE
How can we define `Models.variable_names(::EDMF)` for multiple updrafts?

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaAtmos.jl#238]
For EDMF, we have multiple updrafts (n-tuple fields). How would we define `Models.variable_names(::EDMF)`? My understanding of what ClimaAtmos expects is something like:

```julia
Models.variable_names(tc::EDMF) = (
    :ρarea_up_1,
    :ρarea_up_2,
    )
```

We _could_ make this with something like `ntuple(i-> Symbol("ρarea_up_$i"), n_updrafts(edmf))`, but then it's now clear how we'd loop over them.

This is how we solved this problem in TC.jl: we combined our `variable_names`, `variable_types` into one function, `vars(::Model)`, which returns a `NamedTuple` with all of the proper symbols and types. Our spaces are split into two functions (`face_`, and `cent_`):

```julia
cent_prognostic_vars_en(FT) = (; ρatke = FT(0), ρaHvar = FT(0), ρaQTvar = FT(0), ρaHQTcov = FT(0))
cent_prognostic_vars_edmf(FT, edmf) = (;
    turbconv = (;
        en = cent_prognostic_vars_en(FT),
        up = ntuple(i -> cent_prognostic_vars_up(FT, edmf.entr_closure), n_updrafts(edmf)),
        pr = (; q_rai = FT(0), q_sno = FT(0)),
    ),
)
# cent_prognostic_vars_edmf(FT, edmf) = (;) # could also use this for empty model

# Face only
face_prognostic_vars_up(FT) = (; ρaw = FT(0))
```

We'd be happy to use the existing interface, but I'm not sure how to conform to it with our n-tuple fields. I can't think of any functionality that we'd lose with TC's approach.

Thinking about this more, maybe what we need is something like:

```julia
Models.variable_names(tc::TC.EDMF) = (:up, :en, :pr)
Models.variable_names(up::TC.UpdraftModel) = (:ρarea, :ρaθ_liq_ice, :ρaq_tot) # a component of EDMF
Models.variable_names(tc::TC.PrecipModel) = (:up, :en, :pr)
```

The problem with this is that `default_initial_conditions`, which seems pretty complicated already, would need to be able to work with more highly nested components / subcomponents. Whatever solution we land on, I would prefer / recommend that we minimize the number of places where we make assumptions about the structure of the model.

cc @bischtob, @jiahe23

**Comment by jiahe23** [comment]
can you do something like
```
Models.variable_names(tc::EDMF) = (
    :ρarea_up,
    :ρarea_en,
    )
```
where `ρarea_up` is a n-tuple for all updrafts?

**Comment by jiahe23** [comment]
actually, do we need `en` in the prognostic vars (tke might be the only thing we need?)? If I understand it correctly, other env vars are computed directly from upd and grid mean?

**Comment by bischtob** [comment]
The only three design considerations I can see for how we define our variable, types, and spaces templates are:

1. We may not want to bake into the variable names any center or face pre- or suffixes because where the variables live may be different in the future and we don’t want to rename everything then. However, I don't mean to suggest renaming all EDMF variables now. I think this is just something to keep in mind for future requests as our names will spread everywhere (diagnostics, etc.) eventually.
2. We may want to keep our nesting structure nice and clean to allow model modularity and easy access in diagnostics without passing the whole forest around. To that end, I have no preference how we achieve that. I think the current TC way of doing it is reasonably close to the CA way of doing things already (philosophically speaking :)).
3. I'd love if we could simplify and rename the `default_initial_conditions` function as it really is there because if DiffEqBase.jl. I feel that it would be more natural if DiffEqBase.jl interface functions lived in the Simulations.jl module.

**Comment by charleskawczynski** [comment]
> can you do something like
> 
> ```
> Models.variable_names(tc::EDMF) = (
>     :ρarea_up,
>     :ρarea_en,
>     )
> ```
> 
> where `ρarea_up` is a n-tuple for all updrafts?

No, I think it's better that we group all updraft variables as I've outlined (where `up` is a `NamedTuple`). Perhaps it's not so much the variable names that are the issue (I've updated my post to show how our variables are organized.), I think that this may work:
```julia
Models.variable_names(tc::TC.EDMF) = (:up, :en, :pr)
Models.variable_names(up::TC.UpdraftModel) = (:ρarea, :ρaθ_liq_ice, :ρaq_tot) # a component of EDMF
Models.variable_names(tc::TC.PrecipModel) = (:up, :en, :pr)
```
But I'll need to think more about the variable types and spaces. It would be helpful to hear what people envisioned with this interface.
