### ISSUE TITLE
Distributed Moist Held Suarez GPU simulation crashes in diagnostics

### ISSUE THREAD

**Issue by sriharshakandala** [CliMA/ClimaAtmos.jl#2507]
The 4-process Moist Held Suarez GPU simulation is crashing with the following error:

```
ERROR: LoadError: Could not compute diagnostic Surface Altitude: NCDatasets.NetCDFError(-101, "Opening path gpu_hs_rhoe_equil_55km_nz63_0M/orog_inst.nc: NetCDF: HDF error")
```

The detailed error message can be found here:
https://buildkite.com/clima/climaatmos-target-gpu-simulations/builds/168#018cf9bf-e9cb-492b-8049-ad3cac9df2e6

**Comment by Sbozzolo** [comment]
I think these are separate issues. #2507 occurs more or less randomly and it is due to the fragile nature of distributed file systems. There's not much we can do, I think. Rerunning the job should do the trick.

#2505 will be fixed by https://github.com/CliMA/ClimaAtmos.jl/pull/2489/commits/b0b3ec3c504f610cf5bb4014a4942e794a38c98f

**Comment by Sbozzolo** [comment]
Duplicated of #2425
