### ISSUE TITLE
output default diagnostics significantly decreases SYPD in some longrun jobs

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaAtmos.jl#2641]
Setting output default diagnostics to true results in a large decrease in SYPD in several longrun jobs. Here are several builds from the latest main branch:
GPU, with diagnostics: https://buildkite.com/clima/climaatmos-gpulongruns/builds/41
GPU, without diagnostics: https://buildkite.com/clima/climaatmos-gpulongruns/builds/42
CPU, with diagnostics: https://buildkite.com/clima/climaatmos-longruns/builds/1428
CPU, without diagnostics: https://buildkite.com/clima/climaatmos-longruns/builds/1429

Here are SYPD for different jobs (I cancelled some jobs, but you can see the SYPD from the progress information):
```
GPU

longrun_bw_rhoe_equil_highres
with diagnostics: 14.529
without diagnostics: 26.946

longrun_hs_rhoe_equil_55km_nz63_0M
with diagnostics: 9.063
without diagnostics: 9.435

longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_0M
with diagnostics: 5.187
without diagnostics: 5.366

longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_diagedmf_0M
with diagnostics: 0.123
without diagnostics: 0.526

longrun_aquaplanet_rhoe_equil_55km_nz63_allsky_diagedmf_0M
with diagnostics: 0.124
without diagnostics: 0.524
```
```
CPU

longrun_aquaplanet_rhoe_equil_55km_nz63_gray_0M
with diagnostics: 0.78
without diagnostics: 0.975

longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_diagedmf_diffonly_0M
with diagnostics: 0.143
without diagnostics: 0.176

longrun_aquaplanet_dyamond
with diagnostics: 0.013
without diagnostics: 0.021

longrun_aquaplanet_amip
with diagnostics: 0.121
without diagnostics: 0.152
```
I wonder why there is such a difference for different jobs. The numbers for CPU jobs may not be very reliable as there are large differences between different nodes, but the difference in `longrun_aquaplanet_dyamond` seems significant. The GPU jobs are on the clima cluster. `longrun_bw_rhoe_equil_highres` has instantaneous diagnostics, and both `diagedmf` jobs have a lot more diagnostics. Is it simply because more memory is needed for more diagnostics? I will try reducing the number of diagnostics in those jobs and see if it makes a difference.

cc @Sbozzolo @charleskawczynski

**Comment by charleskawczynski** [comment]
I think most of the performance hit is coming from that the calls to `NCDatasets.sync` (based on the flame graph). This will impact both CPU and GPU jobs, since this call occurs on the CPU in both cases. It's more noticeable on the GPU jobs because we reach the diagnostics quicker, and so it has a larger impact. Can we just move the calls to `NCDatasets.sync` to after `solve!`? We're already planning to move `solve!` to ClimaAtmos, so that we can wrap the `step!` calls in a try-catch (#2571). This is probably the lowest hanging fruit improvement.

The second most expensive thing is the call to ClimaCore's `interpolate_column`-- we should probably change that to a non-allocating version (we can keep support for an allocating method that calls `similar` and then uses the non-allocating method). This might require more work, based on how the diagnostics are organized.

**Comment by szy21** [comment]
I forgot that the default diagnostics contain pretty frequent (30 min) instantaneous diagnostics for edmf jobs. So all three jobs that are slow on GPU have instantaneous diagnostics. Maybe there is some hint? I will remove instantaneous diagnostics in the longrun edmf jobs tomorrow, as we don't need them.

**Comment by Sbozzolo** [comment]
> I think most of the performance hit is coming from that the calls to `NCDatasets.sync` (based on the flame graph). This will impact both CPU and GPU jobs, since this call occurs on the CPU in both cases. It's more noticeable on the GPU jobs because we reach the diagnostics quicker, and so it has a larger impact. Can we just move the calls to `NCDatasets.sync` to after `solve!`? We're already planning to move `solve!` to ClimaAtmos, so that we can wrap the `step!` calls in a try-catch (#2571). This is probably the lowest hanging fruit improvement.`

`NCDatasets.sync` is writing to disk. When we didn't have `sync`, writing to disk happened on `nc[XXXX] = interpolatedXXX` for CPU runs (read: `sync` does nothing for CPU runs), or when the files were closed on GPU runs. This led to all sorts of problems, and we most definetely don't want to keep in memory that amount of data. 

In https://github.com/CliMA/ClimaAtmos.jl/pull/2623 I tried to `sync` only once per cycle, but the peformance jobs seem much slower. But maybe that's again because those cases are not well suited to test the diagnostics.

> The second most expensive thing is the call to ClimaCore's interpolate_column-- we should probably change that to a non-allocating version (we can keep support for an allocating method that calls similar and then uses the non-allocating method). This might require more work, based on how the diagnostics are organized.

I agree. We can revisit this once we have better infrastructure for regridding.

> One other thing I noticed, when working in TC with a lot of variables, was that opening and leaving files open was more performant than open-close open-close: https://github.com/CliMA/TurbulenceConvection.jl/pull/1214#issuecomment-1167826446. I don't know how significant this is for us, but it's worth thinking about.

NetCDF files are all already opened only once.

I don't trust the flame graphs that we have in have in the Atmos CI to really tell me where the bottleneck. For example, `sync` is called only at output (not at compute). For daily averages with timestep of 100 s, that's once every 864 steps, amortizing the cost.

As we were discussing on Monday, we need a realistic benchmark case.

**Comment by Sbozzolo** [comment]
Let me add that the behavior for `sync` on CPU/GPU runs is not documented, and the message with regards to when writing happens on GPU runs is from empirical tests. It might be dependent on other factors.

**Comment by charleskawczynski** [comment]
> NCDatasets.sync is writing to disk. When we didn't have sync, writing to disk happened on nc[XXXX] = interpolatedXXX for CPU runs (read: sync does nothing for CPU runs), or when the files were closed on GPU runs. This led to all sorts of problems, and we most definetely don't want to keep in memory that amount of data.

Yes, `sync` forces writing to disk. Where did it lead to problems? Is there an issue? `sync` isn't absolutely necessary, as the docs suggest (https://docs.unidata.ucar.edu/netcdf-c/current/group__datasets.html#gaf2d184214ce7a55b0a50514749221245):

> I don't trust the flame graphs that we have in have in the Atmos CI to really tell me where the bottleneck.

Why is this? The flame graphs match what we're seeing in the long runs.

> For example, sync is called only at output (not at compute).

What do you mean by at output, not at compute?

...

I've spent a fair bit of time on performance of IO in TurbulenceConvection, have you compared what we have in ClimaAtmos with what we're doing there? In TC, what we have looks like:

```julia
function write_field(
    self::NetCDFIO_Stats,
    var_name::String,
    data::T,
    group,
) where {FT <: AbstractFloat, T <: AbstractArray{FT, 1}}
    # Hack to avoid https://github.com/Alexander-Barth/NCDatasets.jl/issues/135
    @inbounds self.vars[group][var_name][:, end] = data
end

function add_write_field(
    ds,
    var_name::String,
    data::T,
    group,
    dims,
) where {FT <: AbstractFloat, T <: AbstractArray{FT, 1}}
    grp = ds.group[group]
    NC.defVar(grp, var_name, FT, dims)
    var = grp[var_name]
    var .= data::T
    return nothing
end
```

One really simple issue that I see we can fix is that `@inbounds` is missing in, e.g., `v[time_index, :, :, :] = interpolated_field`. The other thing that, IIRC, helped was using a function barrier for the array that is being written to disk, giving NCDatasets the best shot at knowing the array and element type (https://docs.julialang.org/en/v1/manual/performance-tips/#kernel-functions).

**Comment by Sbozzolo** [comment]
> What do you mean by at output, not at compute?

Diagnostics are computed and accumulated at every iteration, but interpolated and output only once every now an then (e.g., every day). The flame graph is profiling a step when the output occurs, but that's not necessarily representative. The the limit with very large output time: it doesn't matter how much `sync` and `interpolate` cost if they are only called once in a blue moon.

I want to see a run with a realistic number of diagnostics a realistic output frequency, and profile one full cycle. I will be working on this now. With that, we can assess what to do next.

**Comment by charleskawczynski** [comment]
Sounds good, can you share the flame graph once you've generated one?

**Comment by Sbozzolo** [comment]
Flame in https://buildkite.com/clima/climaatmos-target-gpu-simulations/builds/193#018d85a0-e4e4-4785-b982-dd1615dccf78

![image](https://github.com/CliMA/ClimaAtmos.jl/assets/9167485/2456c569-b8ed-49db-ae4d-abe9268ea87a)

**Comment by Sbozzolo** [comment]
This should fix the problem on the compute side (not on the IO side):
https://github.com/CliMA/ClimaCore.jl/pull/1610
