### ISSUE TITLE
re-running add_diagnostic_variable! produces error (in coupler)

### ISSUE THREAD

**Issue by juliasloan25** [CliMA/ClimaAtmos.jl#2709]
In Atmos's diagnostics, trying to add a diagnostic that's already been added results in an error (in [this line](https://github.com/CliMA/ClimaAtmos.jl/blob/main/src/diagnostics/diagnostic.jl#L155-L156)). When debugging in the coupler, we often re-run our driver from the same julia session (using Revise for changes). However, we've recently added some calls to `add_diagnostic_variable!` in our driver that are causing our runs to fail when we re-run in a session that's already added the diagnostics

(this isn't really a bug, but it is a little annoying and has an easy fix :) )

### Proposed solution
Do nothing if a variable is already in the diagnostics, instead of failing with an error

### Example error message
(in ClimaCoupler.jl experiments/AMIP, after running `include("coupler_driver.jl")` in the same julia session)

> julia> include("coupler_driver.jl")
> ERROR: LoadError: diagnostic mse already defined
> Stacktrace:
>  [1] error(s::String)
>    @ Base ./error.jl:35
>  [2] #add_diagnostic_variable!#3
>    @ ClimaAtmos.Diagnostics ~/.julia/packages/ClimaAtmos/9h5KM/src/diagnostics/diagnostic.jl:155 [inlined]
>  [3] top-level scope
>    @ ~/ClimaCoupler.jl/experiments/AMIP/components/atmosphere/climaatmos_extra_diags.jl:16
>  [4] include(fname::String)
>    @ Base.MainInclude ./client.jl:489
>  [5] top-level scope
>    @ ~/ClimaCoupler.jl/experiments/AMIP/components/atmosphere/climaatmos_init.jl:17
>  [6] include(fname::String)
>    @ Base.MainInclude ./client.jl:489
>  [7] top-level scope
>    @ ~/ClimaCoupler.jl/experiments/AMIP/coupler_driver.jl:126
>  [8] include(fname::String)
>    @ Base.MainInclude ./client.jl:489
>  [9] top-level scope
>    @ REPL[1]:1
> in expression starting at /Users/jsloan/ClimaCoupler.jl/experiments/AMIP/components/atmosphere/climaatmos_extra_diags.jl:16
> in expression starting at /Users/jsloan/ClimaCoupler.jl/experiments/AMIP/components/atmosphere/climaatmos_init.jl:17
> in expression starting at /Users/jsloan/ClimaCoupler.jl/experiments/AMIP/coupler_driver.jl:126

**Comment by juliasloan25** [comment]
@Sbozzolo is the proposed solution okay with you?

**Comment by Sbozzolo** [comment]
These are behaviors that I think would minimize errors:
1. If a variable already exists and you trying adding something with the same name, error out (current behavior)
2. If a variable already exists and you trying adding something wth the same name, check if the new one is identical to the old one, if yes, do nothing, if not error out
3. If a variable already exists and you trying adding something wth the same name, check if the new one is identical to the old one, if yes, do nothing, if not warn the user and overwrite it

Unfortunately, it is pretty much impossible to meanigully compare two variables because one of the fields is a function. For your particular case, however, I think you'd be able to compare everything because the function will also the very same function. So, I'd recommend implementing 2. This is achieved by extending the check to check for all the fields that are passed against what is in ALL_DIAGNOSTICS.
