### ISSUE TITLE
The `sphere_aquaplanet_rhoe_equilmoist_allsky` job is unstable.

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaAtmos.jl#624]
See [this build](https://buildkite.com/clima/climaatmos-ci/builds/2026#0181f32e-7b47-4055-ac17-f2d105d87c72). We need to reduce the timestep. To ensure it's stable.

**Comment by charleskawczynski** [comment]
@szy21 Regarding [this comment](https://github.com/CliMA/ClimaAtmos.jl/pull/620#issuecomment-1186043363):

> Right, but it was fine before, so some recent PRs lead to failures now, which I don't understand. It's possible that we were just lucky before:)

I'm not even sure that this job was ever stable. Here's a screenshot of the solution during the animation when this job was first added in #513:

<img width="588" alt="Screen Shot 2022-07-16 at 1 40 51 PM" src="https://user-images.githubusercontent.com/1880641/179371370-8b8fd0f1-bfde-41e4-97d0-59e14f8f5d4d.png">

@dennisYatunin, since you added this, can you take a look since it's holding up other PRs/CI in general? Maybe this job depends on random numbers without a seed? I'm not really sure / familiar, but it needs to be addressed.

**Comment by szy21** [comment]
The screenshot you have is for `sphere_single_column_radiative_equilibrium_allsky_idealized_clouds` I think, not this job?

**Comment by charleskawczynski** [comment]
Okay, so it very well may be that both are unstable. No regression tests were added, so it’s difficult for me to tell if the sphere case was.

**Comment by szy21** [comment]
The oscillation at the beginning of this simulation may result from the large heating rate due to an idealized and unrealistic cloud field, I think. Similarly, the cloud field in the sphere case is also unrealistic. That's the main reason we didn't add a regression test. Given that it is unrealistic, I am not too concerned that it is unstable now, and we can remove this test. What I am more concerned about is if it makes sense that one or more recent PRs change the behavior of this job somewhat substantially (in 513 it can run for 5 days at least with dt=200s but now it can't run for 1 day with dt=100s).

**Comment by charleskawczynski** [comment]
> What I am more concerned about is if it makes sense that one or more recent PRs change the behavior of this job somewhat substantially (in 513 it can run for 5 days at least with dt=200s but now it can't run for 1 day with dt=100s).

This is what the regression test infrastructure is for-- to track behavioral changes. Also, we don't know that it can't run for 5 days at least with dt=200s, it's just (at the very least) flakey. The more I think about this, it seems that this job somehow depends (depended) on random numbers. I'm not sure what else could explain the different behavior between the staging and main branches.

The first question we should answer is: is this job important (or a stepping stone towards an important job) or not?
 - If it is, I don't think simply removing the job from CI is the right solution here. We should add it back in, hook in a regression test, and track down where random numbers (or maybe a race condition) is coming into the results.
 - If it's not, then removing is fine.

**Comment by szy21** [comment]
> The first question we should answer is: is this job important (or a stepping stone towards an important job) or not?

It is not very important in my opinion. The problem is, from a moist held suarez to a full aquaplanet model, there are many new processes added, including radiation, surface fluxes, EDMF, etc. But there are not many stepping stones in between because adding only one process is always not physical, so I'm not sure whether we should expect it to be stable. I added this test just to make sure all-sky radiation can run in a spherical setup.
