### ISSUE TITLE
Refactor the TurbulenceConvection argument handling in ClimaAtmos

### ISSUE THREAD

**Issue by trontrytel** [CliMA/ClimaAtmos.jl#721]
## Purpose
The code related goal is to refactor the way we handle simulation arguments and parameters in TC in CA. Right now some of them are passed via command line, while others are passed by `namelist` files, while others are passed via `toml` files.

The second goal of this project is to onboard a new team member and expose him to the TC and CA structure.

## Cost/Benefits/Risks
Benefits:
- Ensure that parameters passed for a given simulation configuration are the relevant parameters for it
- Ensure that the defaults are defined in one place and not overwritten by defaults in another place
- Embrace more the new `toml` file way of handling parameter values that can be calibrated
Risks:
- The calibration pipeline for EDMF still depends on the `namelist` files. When doing this refactor it would be good to know the specifications for switching the calibration to rely more on the `toml` files and less on the `namelist` files. 

## People and Personnel
(@ the personnel required/requested to implement the software solution)
- Lead: @nefrathenrici 
- Collaborators: @trontrytel 
- Reviewers: @charleskawczynski @dennisYatunin @odunbar @costachris 

## Components

1) Flattening the `namelist` structure in TC (As suggested here: https://github.com/CliMA/TurbulenceConvection.jl/issues/908)
2) Changing the flattened `namelist` file into `toml` file(s). (We could potentially split it between files with parameter values and files with simulation flags).
3) <del> Adding a way to automatically generate a `namelist` file from the `toml` file. This way we would move towards using the new `toml` files from the model interface standpoint, while still keeping the `namelist` file for calibration pipeline. <\del>
4) Identifying which of the `namelist/toml` parameters should also be allowed to be changed via the command line and adding them to cli. 
5) Using ArgParse to group commad line args(?)

## Inputs

We would appreciate some feedback on this from both the calibration side (@costachris, @odunbar) and model development side (@charleskawczynski @dennisYatunin @yairchn). Do points 1-3 make sense for everyone?

From the calibration point of view - do we envision making a new calibration pipeline for CA + TC? Or are we hoping to use CEDMF for the whole model as well? I think that knowing this would help decide if we should start working on parameters from TC or CA+TC

**Comment by odunbar** [comment]
My only concern - likely as I don't know enough about the user experience of running the code - is the movement towards more flags. It seems like we start with a 3 input system
1. command line arguments and flags + Argparsing
2. a structured namelist
3. a flat TOML

I would advocate that at the end of this SDI we will have only a two-input system where a simulation is run when provided with:
1. flat "model parameter values" in TOML 
2. flat namelists containing the rest.
(which would require instead converting argparse to namelist)

I feel would be a valuable step towards the goal of a one input system with only flat TOMLs. (If that is our goal)

**Comment by trontrytel** [comment]
I think command line arguments are heavily used in testing in buildkite. Not sure we want to change any of that now @charleskawczynski

**Comment by dennisYatunin** [comment]
Yeah, we basically need command-line arguments for CI. Since CI is a series of calls to the driver through the command-line with slightly different inputs, we either need to create a separate namelist/TOML for every single experiment, or we need to allow command-line arguments. We could use a namelist/TOML to store default parameter values and have command-line arguments override those, or we could use the command-line argument interface specify the default values and have the namelist/TOML override those, but either way we need command-line arguments in order to avoid having CI turn into an endless sea of parameter-specifying files.

**Comment by dennisYatunin** [comment]
Personally, I would be in favor of storing default values in the command-line argument interface (as we have been doing in ClimaAtmos), since that allows us to run the driver without needing an additional parameter-specifying file. When running the calibration pipeline, the pipeline could generate a namelist/TOML that overrides some of these defaults and only modify that file.

**Comment by odunbar** [comment]
The direction we are headed, is precisely to have one TOML file per model run. The aim being that we can fully specify a model run in a single file, aided by centralized defaults in a controlled repository (`ClimaParameters.jl`). 

If this is the goal then _at some point_ I presume the command line arguments will have to go - so I would just urge caution towards becoming too reliant upon that interface, such as by making it too complex/structured. Otherwise in a couple years there will be another SDI to flatten and remove the argparse interface.

**Comment by charleskawczynski** [comment]
> The direction we are headed, is precisely to have one TOML file per model run

This is not really going to scale well w.r.t. lines of code, and it seems like an unnecessary restriction/constraint. Right now, doing this would mean we need to add, at least, 45 toml files (and filenames!) --that's how many experiments I see in CI.

> If this is the goal then at some point I presume the command line arguments will have to go 

I am strongly against this being the goal, the CL arguments greatly simplify maintaining code and ensuring that code is tested.

> so I would just urge caution towards becoming too reliant upon that interface

It's not really an interface, it's a feature that we support (TC can run with both CL args and a toml file). We support using CL arguments because we have a lot of requirements, and ensuring that we're able to test code in many different configurations is one of such requirements. Restricting us to only being able to run with toml files would make testing many configurations unmanageable.

CL args is actually a really convenient feature to support, too. The toml file is read in as a flat dict, which is perfect, because that's what the parsed args data structure is. These two modes of running should work really well together.

**Comment by trontrytel** [comment]
We talked about this refactoring during amip meeting today with @tapios . His suggestion is to:

1. Work in CA+TC (not in the standalone TC).
2. Remove the namelist files and move the parameters and model choices into toml files and command line arguments.
3. Once we start calibrating in CA we will have to write a new pipeline that interfaces with the toml files. But don't worry about compatibility with how things are done in CEDMF now.

With that in mind, the first two components of this task are still a go and the third one is not needed. @costachris , @ilopezgp if there are things we should avoid doing to make future calibration easier lmk.

**Comment by tapios** [comment]
To add support to what @odunbar says:

1. We will need all parameters exposed in parameter (TOML) files. This was one of our central project goals from the very beginning (see the Roadmap on Overleaf) document. It is necessary for automated calibration of model components (separately and jointly). Basically, our model should be treatable as a black box that takes parameters in (from a file) and outputs model statistics, so we can calibrate all parameters (given their metadata such as priors) by comparing model output with various kinds of data. 

2. ClimaParameters is the way to handle all parameters. We should use it. Is there any good reason not to do so now? (Why would we need some intermediate TOML-based structure that is not ClimaParameters?)

3. Command line arguments are not a manageable way to handle climate model parameters (hundreds soon) in the long run. What is convenient for CI right now should not drive model development. CI must be subordinate to getting to an excellent climate model that is calibrated with observations, not the other way around. There may be a few CL arguments that are useful (e.g., for floating point precision or output frequency), but those should just be a few global parameters.

4. If the above means we have dozens of TOML files for dozens of different tests, this is how it needs to be and should be. (Though there is a question of how many tests we really need in CI. Quality of tests is more important than quantity.)

**Comment by trontrytel** [comment]
Thank you for all the comments. We will have some prototype that uses the CLIMAParameter toml files for the 4 CI cases we have in CA+TC. It will be easier to iron out the kinks once we have a prototype.

**Comment by trontrytel** [comment]
Closing this one. The work has been moved here: https://github.com/CliMA/ClimaAtmos.jl/issues/1259
